### PR TITLE
Draft: update Ducc0 interface

### PR DESCRIPTION
**Pull request by mreineck**
This is a preview of how the Ducc0 wrapper code will change once the `Ducc0.jl` package (which will internally depend on `ducc0_jll.jl`) is released. Unfortunately it's currently hard to say when that will happen, since Yggdrasil's CI has been broken for quite some time, and without that, the release is impossible...

I'll adjust the PR and remove the draft status as soon as things are moving forward again.

### CODE REVIEW

**Comment by tknopp** [comment]
Great that you register Ducc0.jl as dedicated package. Best would be then to also move the wrapper into Ducc0.jl. You would then just need to depend on AbstractNFFTs.jl and implement the interface. In case that you also provide the FFT (which I hope...) then you could also implement AbstractFFTs.jl.

**Comment by mreineck** [comment]
My attempt to make `ducc0` functionality available through the `AbstractFFT` and `AbstractNFFT` interfaces is in this file:
https://github.com/ziotom78/Ducc0.jl/blob/master/src/AbstractInterfaces.jl

Does this look reasonable?

(NB: Ducc0.jl is not released yet, since we are encountering problems on Windows. On Linux, everything should work, however.)

**Comment by tknopp** [comment]
From a first look it looks fine. Not sure where to run unit test though. Makes sense in `Ducc0.jl` but also in this repository. You can copy them from https://github.com/JuliaMath/NFFT.jl/blob/master/test/wrappers.jl as an initial start.

**Comment by mreineck** [comment]
I don't think the test failures are caused by my code ... looks like a segfault in FFTW.

**Comment by mreineck** [comment]
BTW, thanks a lot for the unit tests! I'll definitely add them to the package for the next release.

**Comment by mreineck** [comment]
Thanks!

**Pull request closed without merging**
